apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1 # Sets Image
          ports:
            - containerPort: 5432  # Exposes container port
          env:
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef: 
                 name: db-credentials
                 key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef: 
                 name: db-credentials
                 key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef: 
                 name: db-credentials
                 key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
         claimName: postgresql-data-claim



